# Generated by Django 5.0.1 on 2024-03-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('Gas Leak', 'Gas Leak'), ('Meter Installation', 'Meter Installation'), ('Maintenance', 'Maintenance'), ('Gas Refill', 'Gas Refill')], max_length=100),
        ),
    ]
