# Generated by Django 5.0.1 on 2024-03-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_utility', '0002_alter_servicerequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
